/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer;
import Business.Flight;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sumedhtelang
 */
public class ConfimationFlight extends javax.swing.JPanel {

    /**
     * Creates new form ConfimationFlight
     */
    private JPanel rightJPanel;
    private Flight flight;
    private Customer customer;
    ConfimationFlight(JPanel rightJPanel, Flight flight) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.flight = flight;
        txtFlightNumber.setText(String.valueOf(flight.getFlightNumber()));
        groupGender();
        
        txtFlightNumber.setEnabled(false);
        
        for(int i = 0; i<9; i++)
        {
       
          if(flight.getSeatalloted().getSeatAllotment().get(i)!=null)
          {
            if(flight.getSeatalloted().getSeatAllotment().get(i).equals(seatSelect.getItemAt(i).toString()))
            {    
                seatSelect.removeItemAt(i);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Booking full!! No more seats available. Please select another flight !!");
                txtCustName.setEnabled(false);
                txtAreaAddress.setEnabled(false);
                txtFlightNumber.setEnabled(false);
                //txtPhoneNumber.removeAllItems();
                //txtSeatNumber.setEnabled(false);
                rbtnMale.setEnabled(false);
                rbtnFemale.setEnabled(false);
            }
          }
       
       }
    }
    
    public void groupGender()
    {
        ButtonGroup bgg = new ButtonGroup();
        bgg.add(rbtnMale);
        bgg.add(rbtnFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBookTicket = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        seatSelect = new javax.swing.JComboBox<>();
        txtSeatSelected = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 153));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("ENTER CUSTOMER DETAILS");

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        txtAreaAddress.setColumns(20);
        txtAreaAddress.setRows(5);
        jScrollPane1.setViewportView(txtAreaAddress);

        jLabel4.setText("Gender");

        rbtnMale.setText("Male");

        rbtnFemale.setText("Female");

        jLabel5.setText("Phone Number");

        jLabel6.setText("Seat Number");

        btnBookTicket.setText("Book Ticket");
        btnBookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTicketActionPerformed(evt);
            }
        });

        jLabel7.setText("Flight Number");

        seatSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1A", "2A", "3A", "1B", "2B", "3B", "1C", "2C", "3C", "1D", "2D", "3D", "1E", "2E", "3E", "1F", "2F", "3F" }));
        seatSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatSelectActionPerformed(evt);
            }
        });

        txtSeatSelected.setText("jTextField1");

        jLabel8.setText("Date");

        txtDate.setText("YYYY-MM-DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 184, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatSelect, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnMale)
                                        .addGap(42, 42, 42)
                                        .addComponent(rbtnFemale)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSeatSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(btnBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbtnMale)
                            .addComponent(rbtnFemale))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(seatSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSeatSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicketActionPerformed
        // TODO add your handling code here:
        customer = new Customer();
           try{ 
            if (txtCustName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Please enter customer name!!");
                return;
            } else {
                customer.setCustomerName(txtCustName.getText());
            }
            
                 if (txtAreaAddress.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Please enter Address!!");
                return;
            } else {
                 customer.setAddr(txtAreaAddress.getText());
            }
                 
                  if (!datePatternCorrect())
        {
            JOptionPane.showMessageDialog(null, "Date should be in the form : MM/DD/YYYY");
             return;
        }
            
            
            customer.setContactNo(Integer.parseInt(txtPhoneNumber.getText()));
           
           
           
            int key = seatSelect.getSelectedIndex();
            String value = seatSelect.getSelectedItem().toString();
            flight.getSeatalloted().populateHashMap(key, value);
            
            
            String selected = seatSelect.getSelectedItem().toString();
            customer.setSeatNo(selected);
     
            //String value = seatalloted.getSelectedItem().toString();
             //customer.setSeatNo(value);
            
            //JOptionPane.showMessageDialog(null, "Your Ticket has been booked");
            
            AskConfirmation askconfirm = new AskConfirmation(rightJPanel, flight, customer);
            rightJPanel.add("AskConfirmation", askconfirm);
            CardLayout layout = (CardLayout) rightJPanel.getLayout();
            layout.next(rightJPanel);
            }catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Please enter number values for Phone Number!!", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBookTicketActionPerformed

    private void seatSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatSelectActionPerformed
   private boolean datePatternCorrect(){
            Pattern p = Pattern.compile("^[0-9]{4}+/[0-9]{2}+/[0-9]{2}+$");
    Matcher m = p.matcher(txtDate.getText());
    boolean b = m.matches();
    return b;
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnBookTicket;
    javax.swing.ButtonGroup buttonGroup1;
    javax.swing.ButtonGroup buttonGroup2;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JRadioButton rbtnFemale;
    javax.swing.JRadioButton rbtnMale;
    javax.swing.JComboBox<String> seatSelect;
    javax.swing.JTextArea txtAreaAddress;
    javax.swing.JTextField txtCustName;
    javax.swing.JTextField txtDate;
    javax.swing.JTextField txtFlightNumber;
    javax.swing.JTextField txtPhoneNumber;
    javax.swing.JTextField txtSeatSelected;
    // End of variables declaration//GEN-END:variables
}
